name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  GRADLE_OPTS: -Dhttp.keepAlive=false

jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch

  build-linux:
    name: Gradle assemble and spotless check
    needs: ["Get-CI-Image-Tag"]
    strategy:
      fail-fast: false
      matrix:
        jdk: [24]
        platform: [ubuntu-latest]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    container:
      # using the same image which is used by opensearch-build to build the OpenSearch Distribution
      # this image tag is subject to change as more dependencies and updates will arrive over time
      image: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-version-linux }}
      # need to switch to root so that github actions can install runner binary on container without permission issues.
      options: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-options }}
    
    steps:
      - name: Run start commands
        run: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-command }}
      
      - name: Set up JDK for build and test
        uses: actions/setup-java@v5
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: ${{ matrix.jdk }}
      
      - name: Checkout opensearch-storage-encryption
        uses: actions/checkout@v5
      
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true
          arguments: |
            assemble -Dbuild.snapshot=false
      
      - name: Switch to ci-runner user and run tests
        run: |
          chown -R ci-runner:ci-runner $GITHUB_WORKSPACE
          find $GITHUB_WORKSPACE -type d -exec chmod 755 {} \;
          find $GITHUB_WORKSPACE -type f -exec chmod 644 {} \;
          chmod +x $GITHUB_WORKSPACE/gradlew
          # Preserve environment variables when switching users
          su ci-runner -c "export JAVA_HOME=$JAVA_HOME && export GRADLE_OPTS='$GRADLE_OPTS' && cd $GITHUB_WORKSPACE && ./gradlew check -x internalClusterTest -Dbuild.snapshot=false"
      
      - name: Fix test results ownership
        if: always()
        run: chown -R root:root $GITHUB_WORKSPACE/build/test-results/ || true
      
      - name: Configure git for test reporter
        if: always()
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: 'build/test-results/test/TEST-*.xml'
          reporter: java-junit
          fail-on-error: false
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.platform }}-JDK${{ matrix.jdk }}-build-reports
          path: |
            ./build/reports/
            ./build/distributions/
